name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: CodewithSegNet/CodewithSegNet
          TARGET_PATH: README.md
          TARGET_BRANCH: master
          SECTION_NAME: wakatime
          COMMIT_BY_ME: true
          COMMIT_MESSAGE: "chore (README): update wakatime stats"
          COMMIT_USERNAME: SegunWakaTime
          COMMIT_EMAIL: "commits@emmanuel.ru"
          SHOW_UPDATED_DATE: false
          SHOW_LINES_OF_CODE: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_PROJECTS: false
          SHOW_LANGUAGE: true
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
          SHOW_TOTAL_CODE_TIME: false
          SHOW_EDITORS: false
          SHOW_PROFILE_VIEWS: true
